Feature: ML overlay template generation
  This repository's templates/ml Copier template must keep producing a
  working house-price ML pipeline when overlaid onto a project already
  generated by templates/python-project (template-generation capability).

  Scenario: Overlay onto a freshly generated python-project produces a working ML pipeline
    Given a temporary directory
    When the user runs "uv tool run copier copy {repo_root}/templates/python-project {tmp_dir}/project --data package_name=house_price --defaults --trust"
    Given the content of "{tmp_dir}/project/house_price/.answers/.python_project.yml" is remembered
    When the user runs "uv tool run copier copy {repo_root}/templates/ml {tmp_dir}/project/house_price --trust"
    Then the command exits with code 0
    And the following files exist: {tmp_dir}/project/house_price/.answers/.ml.yml, {tmp_dir}/project/house_price/src/house_price/estimator.py, {tmp_dir}/project/house_price/webapp/app.py, {tmp_dir}/project/house_price/docker/Dockerfile
    And the file "{tmp_dir}/project/house_price/.answers/.python_project.yml" still matches the remembered content
    When the user runs "uv run poe check" in "{tmp_dir}/project/house_price"
    Then the command exits with code 0
    When the user runs "uv run python -m house_price.tasks.train_model" in "{tmp_dir}/project/house_price"
    Then the command exits with code 0
    And the following files exist: {tmp_dir}/project/house_price/models/model.pkl
    Given docker is available
    When the user runs "docker build -f docker/Dockerfile -t house_price_bdd_test ." in "{tmp_dir}/project/house_price"
    Then the command exits with code 0

  Scenario: Running templates/ml against a destination without templates/python-project fails clearly
    Given a temporary directory
    When the user runs "uv tool run copier copy {repo_root}/templates/ml {tmp_dir}/project --data package_name=house_price --defaults --trust"
    Then the command exits with a non-zero code
    And the output contains "templates/python-project"
